### ISSUE TITLE
Fix panics due to bad offsets when calling rowan `token_at_offset`

### ISSUE THREAD

**Issue by withered-magic** [withered-magic/starpls#146]
Currently only see this behavior in Zed, but pretty often can get errors like

```
stderr: server: initializing state and starting event loop
stderr: server: determining workspace output_base
stderr: server: running "bazel info build-language"
stderr: thread '<unnamed>' panicked at external/crates__rowan-0.15.15/src/cursor.rs:751:9:
stderr: Bad offset: range 0..43 offset 47
stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr: Rayon: detected unexpected panic; aborting
```

Haven't seen this at all in VSCode, so I'm thinking it's maybe something Zed specific about the order in which it delivers `textDocument/didChange` notifications and positional requests like goto def

**Comment by withered-magic** [comment]
@zaucy FYI, addressing this here in case you've seen this with Zed

**Comment by zaucy** [comment]
I actually haven't ran into this! Or I just haven't noticed. Could be platform dependent? I'm mainly running on Windows right now.

**Comment by withered-magic** [comment]
Hmm, potentially, not familiar enough with how Zed does LSP to be sure tho.. either way it should be fixed across platforms now!
