### ISSUE TITLE
Add Homebrew `brew` formulae option for macOS install

### ISSUE THREAD

**Issue by erikkerber** [withered-magic/starpls#185]
`brew install starpls` would fit well into many developer workflows, and would also solve for the chmod/quarantine/`PATH` dance required to download and run the binary from GitHub.

**Comment by withered-magic** [comment]
This makes sense and seems much more straightforward to deal with on Mac! I'll try to get this out soon and update the docs when ready

**Comment by withered-magic** [comment]
This should be working now, and the `README` is now updated - let me know if you run into any issues with the brew installation!
