### ISSUE TITLE
Support document symbols (`textDocument/documentSymbol`)

### ISSUE THREAD

**Issue by withered-magic** [withered-magic/starpls#220]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol

**Comment by zaucy** [comment]
I'm curious if "document symbols" in starlark would include bazel/buck targets?

i.e. would this

```starlark
_some_local_var = []

cc_library(name = "some_target")
```

result in these symbols?

```
_some_local_var
:some_target
```

same question for for "workspace symbols" https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_symbol

**Comment by withered-magic** [comment]
Yep, that's what I'm envisioning! Although the initial implementation here would likely use the same heuristic that goto def for labels currently uses and derive the list of targets from call expressions that have a `name` argument
