### ISSUE TITLE
Support Bazel prelude

### ISSUE THREAD

**Issue by Strum355** [withered-magic/starpls#231]
Currently, starpls will error when you try to reference something that is coming from the prelude file. Our use case is having a set of global variables teams can use to tag targets with e.g. `tags = [TAG_TEAMXYZ]`

References: 
https://github.com/bazelbuild/bazel/issues/11940
https://github.com/bazelbuild/bazel/issues/1674
https://stackoverflow.com/questions/61168219/is-there-a-way-to-add-native-rules-to-bazel

**Comment by withered-magic** [comment]
Actually, a quick question: It says that the actual implementation of the prelude file works by prepending its contents to all `BUILD` files, but is it fine for your use case if `starpls` doesn't follow those exact semantics and instead treats it as a file that's implicitly `load`ed? I'd imagine that it would functionally look the same from an IDE perspective but maybe there's a few cases I'm not considering?

**Comment by withered-magic** [comment]
Landed this on `main`! Note that you might have to configure whatever editor you're on to recognize the `prelude_bazel` file as a Starlark file as well
