### ISSUE TITLE
native.register_toolchains not recognized (WORKSPACE mode)

### ISSUE THREAD

**Issue by hauserx** [withered-magic/starpls#248]
In non-bzlmod solution one can use native.register_toolchain. It is not recognized by starpls. Not sure how much priority is there for fixing non-bzlmod cases, but adding here as noticed it.

https://bazel.build/external/migration#register-toolchains

Adding screenshot (as cannot copy-paste those diagnostics):

![image](https://github.com/withered-magic/starpls/assets/32371993/26c776dd-8ec2-4a0f-affc-c0753477cd02)

**Comment by withered-magic** [comment]
I think this is mainly an issue with the exported `native` type from the [builtin proto](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/builtin.proto) missing that member, so it actually doesn't work whether bzlmod is enabled or not I think

The only members available on the `native` module are the ones listed [here](https://bazel.build/rules/lib/toplevel/native) as well as all the builtin rules, so I guess `register_toolchains` isn't part of this set. Should be easy enough to patch the native object though

**Comment by withered-magic** [comment]
Actually I guess we can just include all the functions in this [overrides file](https://github.com/withered-magic/starpls/blob/main/crates/starpls_bazel/data/workspace.builtins.json) on the `native` object, except for `workspace()`.

**Comment by hauserx** [comment]
>  so it actually doesn't work whether bzlmod is enabled or not I think

I maybe worded it incorrectly - register_toolchains cannot be used in MODULE.bazel or extensions, so it will not be a problem  if one uses solely bzlmod. But you are right that even if one enables bzlmod AFAIU then WORKSPACE can still be used (for older deps) and use native.register_toolchains.

> Actually I guess we can just include all the functions in this [overrides file](https://github.com/withered-magic/starpls/blob/main/crates/starpls_bazel/data/workspace.builtins.json) on the native object, except for workspace()

Nice, it should remove the warnings. It will be slightly not precise, as it will sometimes suggest this few methods for non workspace macros/rules, but I guess it will be hard to check whether a given macro is used from WORKSPACE or from BUILD files and use one or another set of methods.

**Comment by withered-magic** [comment]
Opened https://github.com/withered-magic/starpls/pull/249 if you want to add yourself as reviewer!
