### ISSUE TITLE
Uknown type "List"

### ISSUE THREAD

**Issue by hauserx** [withered-magic/starpls#256]
starpls README links this doc about type hinting, but looks it does not work for e.g. List ?
https://peps.python.org/pep-0484/#type-comments

![image](https://github.com/withered-magic/starpls/assets/32371993/3f658a0d-3d1a-4a05-8124-d2b454e981cd)

**Comment by withered-magic** [comment]
Ah it doesn't follow that doc exactly, it uses the types as described in https://github.com/bazelbuild/starlark/blob/master/spec.md#data-types

So in this case you can use `list` instead of `List`

**Comment by hauserx** [comment]
Thanks! Maybe worth changing the main readme?

BTW. If I use `# type: [MyCustomInfo]` it also complains that the `MyCustomInfo` is not defined, but I guess this is the other issue https://github.com/withered-magic/starpls/issues/236
