### ISSUE TITLE
Support `*.BUILD.bazel` files

### ISSUE THREAD

**Issue by withered-magic** [withered-magic/starpls#262]
Sometimes, we have files named something like `foo.BUILD.bazel` which are used as templates or similar. We don't necessarily have to resolve targets declared in these files but we should at least offer nicer completions

**Comment by keith** [comment]
Another case I noticed with this is things like `cc_library` and `glob` don't seem to resolve:

<img width="364" alt="image" src="https://github.com/withered-magic/starpls/assets/283886/78770f45-70e2-479e-849f-3599b9cef7dc">

Also maybe it would be safe to assume that `@//whatever` could be resolved against the current workspace too?

<img width="819" alt="image" src="https://github.com/withered-magic/starpls/assets/283886/0e8b4725-ca3f-48f0-925e-d45ac18ac11e">

**Comment by withered-magic** [comment]
Ah, is this for normal regular `BUILD.bazel` files? Those should work - if not then there's should be logs from the language server around it trying to run `bazel info build-language` and failing. This issue is for a pretty niche use case where files are named something like `foo.BUILD.bazel` and are meant as templates or otherwise inputs to another rule.

As for the `@//whatever` case, that's separate (and unimplemented) for now, I'll open up a separate issue for that

**Comment by withered-magic** [comment]
Here's an example of `cc_library` and `glob` resolving as expected, assuming the `bazel info build-language` invocation worked correctly:


https://github.com/withered-magic/starpls/assets/153045167/8feead3b-ad79-4f0c-a960-8ea1154e76ee

**Comment by keith** [comment]
This is for the case you mentioned. I don't think it's that niche when you're pulling in random C++ dependencies and naming them foo.BUILD

**Comment by withered-magic** [comment]
Ah sounds good, makes sense! Then yeah the behavior you mentioned above is also currently expected, i.e. resolution doesn't work because those globals are only made available in files called `BUILD.bazel`, but should be easy enough to change that check
