### ISSUE TITLE
What's the License? Is it intentionally dual-licensed?

### ISSUE THREAD

**Issue by albertocavalcante** [withered-magic/starpls#278]
I noticed that this project is dual-licensed under both the `MIT` and `Apache 2.0` licenses. Just curious, is there a specific reason for choosing to offer both licenses? Thanks!

**Comment by sluongng** [comment]
I think it was following the practice from the Rust tooling ecosystem. https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/5

**Comment by withered-magic** [comment]
Yep, that was the rationale here, the idea was to copy what both https://github.com/rust-lang/rust and https://github.com/rust-lang/rust-analyzer currently do

**Comment by albertocavalcante** [comment]
Understood. Thanks, @sluongng and @withered-magic!
