### ISSUE TITLE
Enabling starpls in vscode-bazel disables target autocomplete in BUILD.bazel files

### ISSUE THREAD

**Issue by JohnnyMorganz** [withered-magic/starpls#303]
vscode-bazel supports target label autocompletion in BUILD.bazel files by default (https://github.com/bazel-contrib/vscode-bazel/blob/master/src/completion-provider/bazel_completion_provider.ts). However, once we enable starpls by configuring `bazel.lsp.command`, this gets disabled with no alternative (https://github.com/bazel-contrib/vscode-bazel/blob/0bb1fe3da76fb522ffa130db374ecbbafd154a07/src/extension/extension.ts#L58)

It would be nice if this was still possible, either via an equivalent feature in starpls, or by not disabling vscode-bazel autocomplete. I didn't find an equivalent issue for the former, but the latter probably needs to be done on vscode-bazel side. If so, I can move this issue there.

<img width="634" alt="image" src="https://github.com/user-attachments/assets/3d896960-6698-4dfe-94de-c0b309a9d849">

**Comment by withered-magic** [comment]
I think it's probably reasonable to have this functionality in starpls as well! I'm actually not sure if the VSCode autocomplete can be selectively disabled

**Comment by withered-magic** [comment]
Just landed https://github.com/withered-magic/starpls/pull/317 which implements equivalent functionality in the language server - note that this requires you to configure the `--experimental_enable_label_completions` flag

cc @JohnnyMorganz

**Comment by JohnnyMorganz** [comment]
Just tried this out, seems to be working great with equivalent functionality, thank you so much!
