### ISSUE TITLE
Support `attr.string_keyed_label_dict`

### ISSUE THREAD

**Issue by JohnnyMorganz** [withered-magic/starpls#323]
Just a small nice to have
This was introduced in Bazel 7.4: https://bazel.build/versions/7.4.0/rules/lib/toplevel/attr#string_keyed_label_dict, but is not found for starpls

<img width="537" alt="image" src="https://github.com/user-attachments/assets/7b480411-e8e0-47a0-ae83-b0062a2e9b67">

Version: 0.1.16

**Comment by withered-magic** [comment]
Apologies for the slow turnaround here, but just landed https://github.com/withered-magic/starpls/issues/323 which fixes this!
