### ISSUE TITLE
Bazel `prelude_bazel` support broken in versions >= v0.1.15

### ISSUE THREAD

**Issue by arie-stripe** [withered-magic/starpls#337]
I made a bare-boned project to demonstrate that the `prelude_bazel` file isn't being used at all, despite it being found:

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/b94509cf-96bb-4112-80bf-50f4182ec972">

--- 

Confirmed that `prelude_bazel` does work in 13 and 14, but then breaks in 15.

- ✅ v0.1.13
- ✅ v0.1.14
- ❌ v0.1.15
- ❌ v0.1.16
- ❌ v0.1.17
- ❌ v0.1.18

No versions show any errors or different output from the Bazel LSP client.

**Comment by withered-magic** [comment]
Thanks for the report! Put up https://github.com/withered-magic/starpls/issues/338 which should fix this

**Comment by arie-stripe** [comment]
Wow that was so fast! Thank you!

**Comment by arie-stripe** [comment]
@withered-magic not trying to rush, but do you have an idea of when you might release v0.1.19? We can't downgrade past v0.1.15 because there were no linux-arm64 packages available before that version.

**Comment by withered-magic** [comment]
I can cut a release now!

**Comment by withered-magic** [comment]
Just released [v0.1.19](https://github.com/withered-magic/starpls/releases/tag/v0.1.19)!

**Comment by arie-stripe** [comment]
Awesome! Thank you so much
